USE capstone_db;

INSERT INTO users(username, email, password)
    VALUE ('test', 'test@gmail.com', 'password');

set foreign_key_checks = 0;

DELETE FROM capstone_db.resources WHERE id = 4;
DELETE FROM capstone_db.resources WHERE id = 5;
DELETE FROM capstone_db.resources WHERE id = 6;
DELETE FROM capstone_db.resources WHERE id = 1;
DELETE FROM capstone_db.resources WHERE id = 7;


insert into resources (user_id, created_at, description, link, title) values (1, '2022-03-01 13:10:08', 'in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae', 'google.com.hk/odio/porttitor.html', 'Multi-channelled 4th generation capacity');
insert into resources (user_id, created_at, description, link, title) values (1, '2022-05-19 18:48:46', 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', 'stumbleupon.com/aliquet/pulvinar/sed/nisl/nunc/rhoncus/dui.jpg', 'Synergized dedicated frame');
insert into resources (user_id, created_at, description, link, title) values (1, '2022-06-12 13:51:38', 'semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 'a8.net/semper/rutrum.png', 'Team-oriented clear-thinking product');
insert into resources (user_id, created_at, description, link, title) values (1, '2021-12-28 18:54:18', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium', 'topsy.com/ac/leo/pellentesque.xml', 'Optimized full-range functionalities');
insert into resources (user_id, created_at, description, link, title) values (1, '2021-10-23 08:13:57', 'eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin', 'ask.com/et/ultrices/posuere/cubilia/curae.jpg', 'User-friendly even-keeled moderator');
insert into resources (user_id, created_at, description, link, title) values (1, '2022-03-12 20:45:12', 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 'tripadvisor.com/mauris/eget/massa/tempor/convallis/nulla.jsp', 'Extended zero tolerance emulation');
insert into resources (user_id, created_at, description, link, title) values (1, '2021-11-21 11:59:54', 'erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio', 'mac.com/vel/est/donec/odio/justo/sollicitudin.jpg', 'Integrated impactful paradigm');
insert into resources (user_id, created_at, description, link, title) values (1, '2021-12-30 02:59:00', 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna', 'exblog.jp/at/dolor/quis/odio/consequat/varius.aspx', 'Enterprise-wide value-added architecture');
insert into resources (user_id, created_at, description, link, title) values (1, '2022-04-12 17:39:09', 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', 'seesaa.net/accumsan/felis/ut/at.png', 'Universal multimedia contingency');
insert into resources (user_id, created_at, description, link, title) values (1, '2022-04-02 19:56:12', 'duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam', 'rambler.ru/lorem/quisque/ut/erat/curabitur/gravida.json', 'Future-proofed optimizing product');
insert into resources (user_id, created_at, description, link, title) values (1, '2022-04-24 00:55:47', 'nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', 'nhs.uk/consectetuer/eget/rutrum/at/lorem.aspx', 'Sharable encompassing interface');
insert into resources (user_id, created_at, description, link, title) values (1, '2022-05-31 05:15:36', 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo', 'angelfire.com/ac/neque/duis/bibendum/morbi/non/quam.png', 'Centralized radical adapter');
insert into resources (user_id, created_at, description, link, title) values (1, '2022-04-20 01:37:35', 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet', 'icio.us/parturient/montes/nascetur.js', 'Versatile maximized framework');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-02-09 00:29:54', 'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 'netlog.com/ut/volutpat/sapien/arcu/sed/augue/aliquam.js', 'Visionary composite installation');
insert into resources (user_id, created_at, description, link, title) values (2, '2021-12-17 19:02:01', 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 'wired.com/maecenas/pulvinar.js', 'Seamless incremental matrices');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-02-10 09:19:14', 'mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 'fema.gov/quisque/id/justo/sit/amet/sapien/dignissim.jsp', 'Triple-buffered context-sensitive moderator');
insert into resources (user_id, created_at, description, link, title) values (2, '2021-10-04 10:22:51', 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', 'ox.ac.uk/nam/congue/risus/semper.xml', 'Networked static structure');
insert into resources (user_id, created_at, description, link, title) values (2, '2021-11-25 04:10:39', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', 'myspace.com/potenti.jpg', 'Quality-focused multimedia array');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-05-22 18:53:33', 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 'netlog.com/quis/turpis.js', 'Diverse even-keeled ability');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-04-11 04:44:52', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 'wp.com/quis/tortor/id.html', 'Stand-alone grid-enabled core');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-07-14 18:03:15', 'rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'weibo.com/sit/amet/justo/morbi/ut/odio/cras.aspx', 'Fundamental user-facing parallelism');
insert into resources (user_id, created_at, description, link, title) values (2, '2021-11-18 09:20:22', 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', 'ucsd.edu/vestibulum/ante/ipsum/primis/in/faucibus.xml', 'Visionary bifurcated model');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-04-17 17:12:31', 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 'elegantthemes.com/mi/in/porttitor/pede.xml', 'Proactive contextually-based initiative');
insert into resources (user_id, created_at, description, link, title) values (2, '2021-11-14 08:01:04', 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin', 'aol.com/pede/lobortis/ligula.xml', 'Re-engineered multi-state website');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-03-22 09:27:35', 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', 'qq.com/massa/id/nisl.jsp', 'Front-line exuding focus group');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-01-16 21:05:31', 'accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 'nytimes.com/pharetra/magna/vestibulum/aliquet/ultrices/erat/tortor.aspx', 'Phased dynamic function');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-06-27 16:56:39', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 'mapquest.com/proin/at/turpis/a/pede/posuere.html', 'De-engineered 24 hour task-force');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-06-17 10:09:57', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 'e-recht24.de/quam/pede/lobortis/ligula/sit.png', 'Synergistic 3rd generation hub');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-01-16 23:07:29', 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi', 'a8.net/mauris/ullamcorper/purus/sit/amet.png', 'Operative clear-thinking leverage');
insert into resources (user_id, created_at, description, link, title) values (2, '2022-04-10 05:42:14', 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida', 'reference.com/enim/in/tempor/turpis/nec/euismod/scelerisque.html', 'Upgradable systemic initiative');